import { useState } from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'

interface Trade {
  description: string
}

type Trades = Array<Trade> | null

export default function Home() {
  const [leagueId, setLeagueId] = useState(243624)
  const [trades, setTrades] = useState<Trades>(null)

  const handleSubmit = async () => {
    try {
      const res = await fetch(
        `/api/getLeague?id=${leagueId}`
      );
      const data = await res.json();
      console.log(data);
      setTrades(data.trades)
    } catch (err) {
      console.log(err);
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <h2>
          Find your league's trades
        </h2>
        <ul>
          <li>243624</li>
          <li>138965</li>
        </ul>
        <div>

          <label htmlFor='league-id'>League id:</label>
          <input name='league-id' value={leagueId} onChange={(e) => { setLeagueId(e.target.value) }} />
          <button onClick={handleSubmit}>List trades</button>
        </div>
        {trades == null ? null : trades.map(trade => {

          return (<div>
            {trade.description}
          </div>)
        })}
      </main>
    </>
  )
}
